// <auto-generated />
namespace SistemaSemus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatemodelproduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemodelproduto));
        
        string IMigrationMetadata.Id
        {
            get { return "202006111308040_update-model-produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
